# Generated by Django 2.2 on 2020-03-17 08:28

import DjangoUeditor3.DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='摘要标题')),
                ('title2', models.CharField(blank=True, max_length=100, null=True, verbose_name='副标题')),
                ('content', models.TextField(verbose_name='摘要内容')),
                ('number', models.IntegerField(default=0, verbose_name='摘要序号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='最新修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', DjangoUeditor3.DjangoUeditor.models.UEditorField(verbose_name='内容')),
                ('cover_img', models.ImageField(upload_to='images/article_cover_img', verbose_name='封面图片')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='第一次发布时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='最新修改时间')),
                ('view_number', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='公司名称')),
                ('slogan', models.CharField(blank=True, max_length=100, null=True, verbose_name='口号')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='logo')),
                ('big_img', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='首页大背景图片')),
                ('dec', models.TextField(blank=True, null=True, verbose_name='公司简介')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='公司邮箱')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='手机')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='最新修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='Wechat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='微信公众号名称')),
                ('qrcode', models.ImageField(upload_to='images', verbose_name='公众号二维码')),
                ('logo', models.ImageField(upload_to='images', verbose_name='公众号头像')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='最新修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='ViewNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='客户端ip')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='该客户端浏览此文章的次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='最新修改时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Article', verbose_name='浏览的文章')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='最新修改时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='app1.Category', verbose_name='父分类')),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/carousel_img', verbose_name='轮播图图片')),
                ('title', models.CharField(max_length=100, verbose_name='轮播图标题')),
                ('alt', models.TextField(blank=True, null=True, verbose_name='图片不能加载时的描述')),
                ('number', models.IntegerField(default=0, verbose_name='轮播图序号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='最新修改时间')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.Article', verbose_name='轮播图对应文章id')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Category', verbose_name='文章分类'),
        ),
    ]
