# Generated by Django 2.2 on 2020-03-20 10:17

import DjangoUeditor3.DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstracttext',
            name='number',
        ),
        migrations.AlterField(
            model_name='company',
            name='dec',
            field=DjangoUeditor3.DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='公司简介'),
        ),
    ]
