# Generated by Django 2.2 on 2020-05-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200512_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名')),
                ('phone', models.CharField(max_length=100, verbose_name='电话')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='地址')),
            ],
        ),
    ]
