# Generated by Django 2.2 on 2020-03-22 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200321_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='alt',
        ),
        migrations.AlterField(
            model_name='carousel',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carousel', to='app1.Article', verbose_name='轮播图对应文章id'),
        ),
    ]
