# Generated by Django 2.2 on 2020-05-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='是否查阅'),
        ),
    ]
