# Generated by Django 2.2 on 2020-03-22 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200322_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carousels', to='app1.Article', verbose_name='轮播图对应文章id'),
        ),
    ]
