# Generated by Django 2.2 on 2020-05-18 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_message_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最新修改时间'),
        ),
    ]
