# Generated by Django 2.2 on 2020-04-07 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200322_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='company',
            name='qq',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='客服QQ'),
        ),
        migrations.AddField(
            model_name='company',
            name='wechat',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='客服微信'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='app1.Category', verbose_name='文章分类'),
        ),
    ]
