# Generated by Django 2.2 on 2020-04-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200407_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='官网域名'),
        ),
        migrations.AddField(
            model_name='company',
            name='icp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='icp'),
        ),
    ]
