# Generated by Django 2.2 on 2020-04-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20200407_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechat',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='公众号头像'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='微信公众号名称'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='公众号二维码'),
        ),
    ]
